Feature/patient id fetching
SNDStoolers/sndsTools pull request #48
Opened 2024-12-13 15:37 UTC by MarcDibling

Hello 👋,

Je me lance sur ce sujet épineux mais vital. 
Selon ce qui a été proposé dans #28, la stratégie la plus adaptée pour la gestion des bénéficiaires reposerait sur la création d’un référentiel propre et des variables pouvant servir de filtre pour permettre à l’utilisateur d’adapter le processus d’exclusion.

Parmi les points sensibles on retrouve :
- Considérer ou non la table archivée des bénéficiaires
- Conserver ou non l’information BEN_RNG_GEM pour les jointures
- Les inconsistances au niveau de la date de naissance et du code sexe
- Les BEN_NIR_PSA pointant vers plusieurs BEN_IDT_ANO
- Les NIR fictifs

Je propose donc première tentative de fonction permettant, à partir d’une table contenant BEN_NIR_PSA ou BEN_IDT_ANO, d’extraire les BEN_IDT_ANO et l'ensemble des BEN_NIR_PSA + BEN_RNG_GEM associés en marquant les inconsistances, le statut fictif, les PSA sans IDT unique et en considérant, au choix, la table des bénéficiaires archivée.

2024-12-17 14:53 UTC, strayMat commented
Merci énormément pour cette contribution extrêmement utile. Je fais une passe de relecture cette semaine avec des retours !

2024-12-17 14:59 UTC, strayMat commented on R/retrieve_patient_id.R
> +#' présentant inconsistances relatives aux codes sexe.
`présentant des inconsistances`

2024-12-17 15:01 UTC, strayMat commented on R/retrieve_patient_id.R
> +#' sortie est retournée sous la forme d'un tibble.
tibble est un nom un peu technique, je propose de rajouter data frame qui parle à un public plus large : `data frame tibble`

2024-12-17 16:11 UTC, strayMat requested changes
Super contribution @MarcDibling ! Merci beaucoup pour cette fonction très utile !! ❤

J'ai mis plusieurs propositions de changements. Et lorsque tu auras fait les modifs je testerai sur le portail que ça fonctionne. 

Éventuellement si tu te motives et que tu as le temps, tu peux ajouter un fichier qui test la fonction en local avec duckdb en fournissant des fausses données d'exemple. Pour cela tu peux prendre exemple sur ce test :  https://github.com/SNDStoolers/sndsTools/blob/main/tests/testthat/test-extract_hospital_consultations.R  
Mais ne te prends pas la tête avec le testing, je pourrais le faire dans une PR suivante :)

2024-12-17 16:11 UTC, strayMat commented on R/retrieve_patient_id.R
> +  } else { # Save table in Oracle
Tu pourrais rajouter un message utilisateur ici comme on l'a fait dans d'autres fonctions : 

`message(
      glue::glue("Results saved to table {output_table_name} in Oracle.")
    )`

2024-12-17 16:11 UTC, strayMat commented on R/retrieve_patient_id.R
> +  conn <- connect_oracle() # Connect to database
Dans les autres fonctions, on a décidé de n'ouvrir une nouvelle connexion que si c'est nécessaire (si l'utilisateur ne fournit pas une connexion existante (cf. [cette fonction pour référence](https://github.com/SNDStoolers/sndsTools/blob/main/R/extract_long_term_disease.R) : 
```
 connection_opened <- FALSE
  if (is.null(conn)) {
    conn <- connect_oracle()
    connection_opened <- TRUE
  }
  ```

2024-12-17 16:11 UTC, strayMat commented on R/retrieve_patient_id.R
> +    dbDisconnect(conn)
Fermer la connexion, uniquement si on l'a ouverte, sinon on la laisse ouverte (cf. commentaire en début de fonction): 
```
  if (connection_opened) {
    DBI::dbDisconnect(conn)
  }
 ```

2024-12-18 21:12 UTC, ThomasSoeiro reviewed
Merci @MarcDibling et bravo !

Voilà mes suggestions :)

Et un commentaire plus général : Je préfère les fonctions qui font 1 seule chose car plus facile à créer, à documenter et à comprendre pour les utilisateurs. Que penses tu de séparer ta fonction en 2 fonctions correspondant aux 2 cas ?

par exemple `retrieve _psa_from_idt()` pour :
```
#' A partir d'une table avec BEN_IDT_ANO, la fonction retournera
#' l'ensemble des BEN_NIR_PSA+BEN_RNG_GEM associés.
```

et `retrieve_psa_from_psa()` pour
```
#' A partir d'une table avec BEN_NIR_PSA, la fonction retournera
#' l'ensemble des BEN_NIR_PSA+BEN_RNG_GEM associés au BEN_IDT_ANO.
```

2024-12-29 13:55 UTC, MarcDibling commented
Hello,

Merci beaucoup pour tous vos retours ! J’ai essayé de les intégrer au mieux dans cette nouvelle version. Dites-moi ce que vous en pensez :).

Il y a deux points sur lesquels j’aimerais revenir :
- Sur le choix de `psa_twin` vs. `psa_w_multiple_idt` :
`psa_twin` me semble moins approprié que `psa_w_multiple_idt`, qui est beaucoup plus neutre. J’ai donc conservé ce dernier dans la nouvelle version. Ce marquage permet non seulement d’identifier des jumeaux de même sexe (si RG et SLM) mais aussi des patients qui changent de régime. L’utilisateur peut l’interpréter selon ses besoins et s’interroger sur le choix d’inclusion/exclusion adapté à son cas.

- Concernant le dédoublonnage des identifiants: 
Pourquoi demander ou être prudent sur ce point ? L’objectif de cette fonction est, selon moi, de permettre à partir d’une table (dédoublonnée ou non) de récupérer un extrait des référentiels propre à la table d’entrée. Ensuite, il serait possible de joindre cet extrait à la table d’entrée, qui peut comporter plusieurs lignes et d’autres informations que simplement des identifiants. Dans quel cas de figure les doublons poseraient-ils problème ?

Pour le testing (@strayMat), je m’y pencherai dans un second temps, étant donné les nombreuses modifications apportées :). Par ailleurs, il existe des générateurs de données synthétiques (voir [doc_SNDS](https://documentation-snds.health-data-hub.fr/snds/formation_snds/donnees_synthetiques/)) qui pourraient être intégrés au package pour des démos ou des tests. 

Encore merci pour votre relecture, votre patience et vos commentaires !

Marc

2025-01-29 18:17 UTC, strayMat commented on R/retrieve_patient_id.R
> +      all(c("BEN_NIR_PSA", "BEN_RNG_GEM") %in% (tbl(conn, ben_table_name) %>%
L'appel à tbl est [lazy](https://dbplyr.tidyverse.org/reference/tbl.src_dbi.html) donc ça ne change pas grand chose de faire un appel direct à la table ou juste aller chercher les colonnes.

2025-01-29 18:39 UTC, strayMat commented
Top pour tous mes commentaires. Ca a bien été adressé ! Merci beaucoup pour l'effort (et désolé pour le temps de réponse un peu long). Je vais laisser @ThomasSoeiro  résoudre ses threads.

Un point encore à changer : J'étais d'accord avec l'idée de séparer en deux fonctions pour l'utilisateur. En revanche, ce serait bien de ne pas doublonner le code car les deux fonctions sont extrêmement proches. Dans tous les cas, il faudrait copier/coller la documentation oxygen pour que les deux fonctions soient documentées pour l'utilisateur. Actuellement je pense que la doc oxygen bug quand on génère la doc.

2025-01-29 21:47 UTC, ThomasSoeiro commented
Merci @MarcDibling !

> * Sur le choix de `psa_twin` vs. `psa_w_multiple_idt` :
>   `psa_twin` me semble moins approprié que `psa_w_multiple_idt`, qui est beaucoup plus neutre. J’ai donc conservé ce dernier dans la nouvelle version. Ce marquage permet non seulement d’identifier des jumeaux de même sexe (si RG et SLM) mais aussi des patients qui changent de régime. L’utilisateur peut l’interpréter selon ses besoins et s’interroger sur le choix d’inclusion/exclusion adapté à son cas.

D'accord pour garder `psa_w_multiple_idt`, mais peut-être préciser dans la doc ce que ça peut recouvrir (mais il faudrait que quelqu'un confirme que j'ai pas dit de bêtise) : il me semble que c'est très largement des jumeaux. Il y a aussi peut-être des transitions de genre (je pense que si modification de l'état civil il doit y avoir nouveau NIR puisqu'il commence avec un code 1/2 pour le sexe) et probablement des anomalies. 

Aussi, on a `BEN_CDI_NIR = 0` donc `BEN_IDT_ANO = BEN_NIR_ANO` donc je suggère d'être explicite et de changer :

```diff
-     dplyr::mutate(psa_w_multiple_idt = dplyr::n_distinct(BEN_IDT_ANO) > 1) |>
+     dplyr::mutate(psa_w_multiple_idt = dplyr::n_distinct(BEN_NIR_ANO) > 1) |>
```

Enfin, il ne me semble pas que ça permet d'identifier les changements de régimes (pas de changement de NIR, éventuellement changement de `BEN_RNG_GEM`) mais seulement les changement de NIR. Sinon je veux bien une explication 😊 


> * Concernant le dédoublonnage des identifiants:
>   Pourquoi demander ou être prudent sur ce point ? L’objectif de cette fonction est, selon moi, de permettre à partir d’une table (dédoublonnée ou non) de récupérer un extrait des référentiels propre à la table d’entrée. Ensuite, il serait possible de joindre cet extrait à la table d’entrée, qui peut comporter plusieurs lignes et d’autres informations que simplement des identifiants. Dans quel cas de figure les doublons poseraient-ils problème ?

Ma suggestion était pour un utilisateurs novice qui n'a pas fait attention qu'il n'a pas dédoublonné et qui va avoir des soucis avec ses jointures.

2025-03-23 22:51 UTC, MarcDibling commented
Hey,

Voici une nouvelle version ! Merci beaucoup pour vos retours !

En effet, c’était pas top comme ça. J’ai réduit de la duplication de code @strayMat.

J’ai un peu modifié la description. Je propose donc d’utiliser la variable psa_w_multiple_idt_or_nir pour tout couvrir. Est-ce que ça te parait cohérent @ThomasSoeiro ?

L’idée c’est de pouvoir, à partir de n’importe quelle table en entrée (doublons ou pas), récupérer un extrait du référentiel des bénéficiaires à joindre par la suite. Tu proposes simplement d’indiquer dans le description qu’un extrait sera retourné et qu’un « dédoublonnement » est réalisé ou tu penses qu’il est préférable de faire des modifications pour retourner une table avec autant de doublons qu’en entrée @ThomasSoeiro ?

Milles excuses pour le délai de réponse et de MàJ.

Marc

2025-03-24 08:46 UTC, strayMat reviewed
On y est presque. Merci beaucoup pour l'effort et  les changements. J'ai relu et j'ai l'impression de bien comprendre ce qui est fait. 

J'ai fait encore quelques remarques de forme. La plus importante est de mettre les documentations à côté des fonctions correspondantes car là ça fait quelque chose d'étrange quand on build la doc. 

Ensuite il faudra rebase sur la branche main et de mon côté on sera bon pour merger :) 
Si tu as besoin d'aide pour la toute fin, hésite pas à me dire et on se trouvera un moment pour faire ça ensemble!

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
>  #' @description
Top d'avoir dédoublonner le code. Du coup, il faudrait bouger la doc de retrieve_all_psa_from_idt juste avant la fonction correspondante. Là ça fait un truc étrange en mêlant les docs des deux fonctions quand on rend la documentation web.

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
> +    ben_table_name = NULL,
ben_table_name est obligatoire, donc il est inutile de lui mettre une valeur NULL par défaut. De plus, il est habituel de mettre les arguments obligatoires en premier puis de mettre les arguments optionnels.

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
>  retrieve_all_psa_from_psa <- function(conn = NULL,
ben_table_name est obligatoire, donc il est inutile de lui mettre une valeur NULL par défaut. De plus, il est habituel de mettre les arguments obligatoires en premier puis de mettre les arguments optionnels.

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
> +# Function for retrieving PSA from PSA
Il faudrait déplacer la doc de la fonction à côté du code de celle-ci.

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
> +    stop(glue("ben_table_name must contain at least {start_key}"))
il manque le préfixe du package `glue::glue`

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
> +#' 1. psa_w_multiple_idt_or_nir : permet d'identifier les `BEN_IDT_ANO` ou
Mettre le nom des variables entre "`" ?

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
> +#' 1. psa_w_multiple_idt_or_nir : permet d'identifier les `BEN_IDT_ANO` ou
Mettre le nom des variables entre "`" ?

2025-03-24 08:46 UTC, strayMat commented on R/retrieve_patient_id.R
>  #' Cinq variables sont ajoutées en sortie pour aider au processus d'inclusion :
cinq variables *binaires*?

2025-03-26 17:47 UTC, MarcDibling commented
Merci beaucoup pour tes retours @strayMat  !
Voici une version actualisée :)

Marc

2025-03-27 10:16 UTC, strayMat commented on R/retrieve_patient_id.R
> +    ben_table_name = NULL,
tu as bien supprimé le NULL, mais pas mis l'argument en premier.

2025-04-22 18:36 UTC, ThomasSoeiro commented
Salut Marc,

Désolé pour le temps de réponse.

> J’ai un peu modifié la description. Je propose donc d’utiliser la variable psa_w_multiple_idt_or_nir pour tout couvrir. Est-ce que ça te parait cohérent @ThomasSoeiro ?

J'ai pas le temps de creuser donc si personne n'est en mesure de confirmer, il vaut mieux enlever "Ces `BEN_IDT_ANO` sont majoritairement relatifs à des jumeaux du même sexe mais peuvent aussi être associés à des transitions de genre ou des anomalies."
(sauf si tu as vérifié bien sûr !)

> L’idée c’est de pouvoir, à partir de n’importe quelle table en entrée (doublons ou pas), récupérer un extrait du référentiel des bénéficiaires à joindre par la suite. Tu proposes simplement d’indiquer dans le description qu’un extrait sera retourné et qu’un « dédoublonnement » est réalisé ou tu penses qu’il est préférable de faire des modifications pour retourner une table avec autant de doublons qu’en entrée @ThomasSoeiro ?

A toi de trancher 😊 
Mais si tu optes pour le dédoublonnage, oui je pense que c'est utile de le préciser dans la doc

2025-05-19 13:42 UTC, MarcDibling commented
Hello,
Merci pour vos retours. Voici une version mise à jour avec la documentation propre (enfin testée).
J’ai creusé ce point sur les BEN_NIR_PSA associés à plusieurs BEN_IDT_ANO (c.f. figure). Voici ce que j'ai compris:
<img width="1238" alt="B09F86B6-7731-402A-A260-148244B5022A" src="https://github.com/user-attachments/assets/c5d55e63-cf5c-42c6-b959-4502acb25d81" />

J’ai donc précisé dans la doc d’être vigilant sur ce point et mis une source pour pouvoir faire des choix informés en fonction des tables que l’on souhaite requêter (PMSI+DCIR ou uniquement DCIR). 

J’ai aussi précisé que la table en retour est bien dédoublonnée 👍 . 
Marc

2025-05-20 07:50 UTC, strayMat commented on R/retrieve_patient_id.R
> +    ben_table_name = NULL,
Je me suis permis d'accorder entre la documentation et les fonctions l'ordre des arguments.

2025-05-20 08:06 UTC, strayMat commented
Top ! Je me suis permis de corriger une ou deux typos.  C'est bon pour merger je pense. 

@MarcDibling  Tu veux faire le [rebase](https://www.miximum.fr/blog/git-rebase/) toi même ou bien je m'en charge :)

2025-05-20 08:14 UTC, strayMat commented
Par ailleurs, j'aime beaucoup ta figure : il faudrait garder que tu l'as faite et si tu es d'accord, la mettre dans une page de documentation dédiée à la sélection des identifants (genre mini-étude) : #63

2025-05-22 21:06 UTC, strayMat commented
Je me suis occupé de rebase sur la branche main et de fusionner tous les commits dans un seul. J'en profite pour merger la PR dans main. 

Encore bravo @MarcDibling  pour cet excellent travail !! Et merci beaucoup @ThomasSoeiro pour la relecture <3

2025-05-22 21:13 UTC, merged